[package]
name = "prize_escrow"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
soroban-sdk.workspace = true
serde.workspace = true

[dev-dependencies]
soroban-sdk-test.workspace = true
serde.workspace = true

[lib]
crate-type = ["cdylib"]
